export const APP_ENV = {
	VITE_API_URL: import.meta.env.VITE_API_URL,

	PERSONALITY_ANALYSIS_COOLDOWN_DAYS: import.meta.env.VITE_PERSONALITY_ANALYSIS_COOLDOWN_DAYS,
	PERSONALITY_ANALYSIS_MAX_COUNT: import.meta.env.VITE_PERSONALITY_ANALYSIS_MAX_COUNT,

	INSTITUTION_ANALYSIS_COOLDOWN_DAYS: import.meta.env.VITE_INSTITUTION_ANALYSIS_COOLDOWN_DAYS,
	INSTITUTION_ANALYSIS_MAX_COUNT: import.meta.env.VITE_INSTITUTION_ANALYSIS_MAX_COUNT,

	CAREER_ANALYSIS_COOLDOWN_DAYS: import.meta.env.VITE_CAREER_ANALYSIS_COOLDOWN_DAYS,
	CAREER_ANALYSIS_MAX_COUNT: import.meta.env.VITE_CAREER_ANALYSIS_MAX_COUNT,

	ORGANIZATIONS_GOOGLE_FORM_LINK: import.meta.env.VITE_ORGANIZATIONS_GOOGLE_FORM_LINK,
	CONTACT_PHONE: import.meta.env.VITE_CONTACT_PHONE,
}
