import { EXERCISE_TYPE } from '@prisma/client'

export const DEFAULT_THRESHOLDS: Record<EXERCISE_TYPE, number> = {
	[EXERCISE_TYPE.FLASHCARD]: 80,
	[EXERCISE_TYPE.CLOZE]: 70,
	[EXERCISE_TYPE.SENTENCE_REORDER]: 70,
	[EXERCISE_TYPE.MULTIPLE_CHOICE]: 70,
	[EXERCISE_TYPE.DICTATION]: 70,
	[EXERCISE_TYPE.LISTENING_QUIZ]: 70,
	[EXERCISE_TYPE.PRONUNCIATION]: 50,
	[EXERCISE_TYPE.PICTURE_DESCRIPTION]: 60,
}
